USE [master]
GO

/****** Object:  Database [ApartmentDB]    Script Date: 14.05.2015 17:46:52 ******/
CREATE DATABASE [ApartmentDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ApartmentDB', FILENAME = N'E:\Programme\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ApartmentDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ApartmentDB_log', FILENAME = N'E:\Programme\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ApartmentDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ApartmentDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ApartmentDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ApartmentDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ApartmentDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ApartmentDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ApartmentDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ApartmentDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ApartmentDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ApartmentDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ApartmentDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ApartmentDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ApartmentDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ApartmentDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ApartmentDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ApartmentDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ApartmentDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ApartmentDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ApartmentDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ApartmentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ApartmentDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ApartmentDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ApartmentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ApartmentDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ApartmentDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ApartmentDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ApartmentDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ApartmentDB] SET  MULTI_USER 
GO

ALTER DATABASE [ApartmentDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ApartmentDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ApartmentDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ApartmentDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ApartmentDB] SET  READ_WRITE 
GO

